[versions]
versionName = "1.7.2"
versionCode = "107020"
accompanist = "0.25.1"
agp = "7.3.0"
androidX-activity = "1.6.0"
androidX-appCompat = "1.5.1"
androidX-collection = "1.3.0-dev01"
androidX-compose = "1.2.1"
androidX-composeCompiler = "1.3.2"
androidX-core = "1.9.0"
androidX-fragment = "1.5.3"
androidX-lifecycle = "2.5.1"
androidX-room = "2.4.3"
chucker = "3.5.2"
coil = "2.2.2"
coroutines = "1.6.4"
glide = "4.14.1"
kotlin = "1.7.20"
square-okHttp = "4.10.0"
square-retrofit = "2.9.0"
square-moshi = "1.14.0"
srl = "2.0.5"
support = "28.0.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = "com.google.devtools.ksp:1.7.20-1.0.6"
napt = "com.sergei-lapin.napt:1.17"
kotlinter = "org.jmailen.kotlinter:3.12.0"
detekt = "io.gitlab.arturbosch.detekt:1.21.0"

[libraries]
kotlin-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlinX-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinX-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"

androidX-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidX-compose" }
androidX-compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidX-compose" }
androidX-compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidX-compose" }
androidX-compose-material = { module = "androidx.compose.material:material", version.ref = "androidX-compose" }
androidX-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidX-compose" }
androidX-compose-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "androidX-compose" }
androidX-compose-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidX-compose" }

androidX-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidX-activity" }
androidX-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidX-activity" }
androidX-annotation = "androidx.annotation:annotation:1.5.0"
androidX-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidX-appCompat" }
androidX-browser = "androidx.browser:browser:1.4.0"
androidX-cardView = "androidx.cardview:cardview:1.0.0"
androidX-collection = { module = "androidx.collection:collection-ktx", version.ref = "androidX-collection" }
androidX-constraintLayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidX-coordinatorLayout = "androidx.coordinatorlayout:coordinatorlayout:1.2.0"
androidX-core = { module = "androidx.core:core-ktx", version.ref = "androidX-core" }
androidX-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidX-fragment" }
androidX-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidX-lifecycle" }
androidX-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidX-lifecycle" }
androidX-paging = "androidx.paging:paging-runtime:3.1.1"
androidX-recyclerView = "androidx.recyclerview:recyclerview:1.2.1"
androidX-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidX-room" }
androidX-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidX-room" }
androidX-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidX-room" }
androidX-viewPager2 = "androidx.viewpager2:viewpager2:1.0.0"
androidX-webKit = "androidx.webkit:webkit:1.5.0"

square-leakCanary = "com.squareup.leakcanary:leakcanary-android:2.9.1"
square-moshi = { module = "com.squareup.moshi:moshi", version.ref = "square-moshi" }
square-moshi-compiler = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "square-moshi" }
square-okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "square-okHttp" }
square-okHttp-LogInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "square-okHttp" }
square-okHttp-mock = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "square-okHttp" }
square-okHttp-mockJunit5 = { module = "com.squareup.okhttp3:mockwebserver3-junit5", version.ref = "square-okHttp" }
square-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "square-retrofit" }
square-retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "square-retrofit" }
square-retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "square-retrofit" }

google-accompanist-swipeRefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
google-accompanist-systemUiController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
google-gson = "com.google.code.gson:gson:2.9.1"
google-material = "com.google.android.material:material:1.6.1"

chucker-debug = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-release = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
flycoTabLayout = "io.github.h07000223:flycoTabLayout:3.0.0"
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-okhttp3 = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "glide" }
glide-transformations = "jp.wasabeef:glide-transformations:4.3.0"
photoView = "com.github.chrisbanes:PhotoView:2.3.0"
rxJava3-android = "io.reactivex.rxjava3:rxandroid:3.0.0"
rxJava3-java = "io.reactivex.rxjava3:rxjava:3.1.5"
srl-footer = { module = "io.github.scwang90:refresh-footer-classics", version.ref = "srl" }
srl-header = { module = "io.github.scwang90:refresh-header-classics", version.ref = "srl" }
srl-kernel = { module = "io.github.scwang90:refresh-layout-kernel", version.ref = "srl" }
utils = "com.blankj:utilcodex:1.31.0"

[bundles]
androidX-compose = [
  "androidX-compose-ui",
  "androidX-compose-tooling",
  "androidX-compose-tooling-preview",
  "androidX-compose-material",
  "androidX-compose-foundation",
  "androidX-compose-icons-core",
  "androidX-compose-icons-extended"
]
androidX-lifecycle = [
  "androidX-lifecycle-viewModel",
  "androidX-lifecycle-service"
]
androidX-room = [
  "androidX-room-runtime",
  "androidX-room-ktx"
]
accompanist = [
  "google-accompanist-swipeRefresh",
  "google-accompanist-systemUiController"
]
coil = [
  "coil",
  "coil-gif",
  "coil-svg"
]
glide = [
  "glide",
  "glide-okhttp3",
  "glide-transformations"
]
srl = [
  "srl-kernel",
  "srl-header",
  "srl-footer"
]
